name    'lab42-jboss'
version '2.0.7'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/example42/puppet-jboss'
summary 'Puppet module for jboss'
description 'This module installs and manages jboss. Check README.rdoc for details. Puppi is required for some common functions: you can install them without using the whole module. Monitor and firewall dependencies are needed only if the relevant features are enabled'
dependency 'lab42/puppi', '>= 2.0.0'
dependency 'lab42/monitor', '>= 2.0.0'
dependency 'lab42/firewall', '>= 2.0.0'
